// Bundles the nuzlocke data sets (routes/leagues/patches/encounter-tables) into
// a single data.bundle.js that exposes window.NUZ_DATA. Run with:
//   node build-data.mjs
// from the repo root after opening a fresh PowerShell session (so the Node
// install is on PATH).

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
// Repo-root layout: build-data.mjs sits next to index.html (the app), the
// tracker.html redirect stub, data.bundle.js, and the "nuzlocke data sets
// for unique cases" folder.
const DATA_ROOT = join(SCRIPT_DIR, 'nuzlocke data sets for unique cases');
const OUT_PATH = join(SCRIPT_DIR, 'data.bundle.js');
const HTML_PATH = join(SCRIPT_DIR, 'index.html');

const stripBom = s => s.charCodeAt(0) === 0xFEFF ? s.slice(1) : s;
const norm = s => stripBom(s).replace(/\r\n/g, '\n');
const gameKey = filename => basename(filename, '.txt');

// slug → National-Dex id, inverted from the dev dexmap, bundled so the app can
// resolve a sprite URL for ANY species by name without a PokeAPI backfill
// round-trip (POKEMON_DB only covers ~346 curated species; Gen-5+ rely on this).
function loadDexIdBySlug() {
  try {
    const idToSlug = JSON.parse(readFileSync(join(SCRIPT_DIR, '_converters', '_dexmap.json'), 'utf8'));
    const out = {};
    for (const id in idToSlug) out[idToSlug[id]] = +id;
    return out;
  } catch { return {}; }
}

// Regional-form slug → PokeAPI form id (10091 etc.), for the ~60 self-hosted form
// sprites under ./sprites/. Kept SEPARATE from dexIdBySlug (form slugs are excluded
// there) so spriteUrl can resolve "Alolan Diglett" (diglett-alola → 10105) offline,
// without a PokeAPI backfill. Source: _converters/_formmap.json.
function loadFormIdBySlug() {
  try { return JSON.parse(readFileSync(join(SCRIPT_DIR, '_converters', '_formmap.json'), 'utf8')); }
  catch { return {}; }
}

// slug → [Type1, Type2] (Capitalized), bundled so the species picker can show
// type badges for every species without a PokeAPI backfill. Current/latest-gen
// types (gen-correct typing is still applied per-game by the runtime backfill).
function loadTypesBySlug() {
  try {
    return JSON.parse(readFileSync(join(SCRIPT_DIR, '_converters', '_types.json'), 'utf8'));
  } catch { return {}; }
}

// Complete movedex power + damage category, keyed by PokeAPI slug:
// { "<slug>": [power, "P"|"S"|"U"] }. Generated by _converters/fetch-move-stats.mjs.
// Bundled so move details (power/category) resolve fully OFFLINE — the runtime's
// moveData() checks curated MOVE_DATA first (for effect tags), then this, then
// the live PokeAPI backfill. Lets "pre-cache for offline" actually deliver a
// complete app instead of falling back to unknown move data.
function loadMoveStats() {
  try {
    return JSON.parse(readFileSync(join(SCRIPT_DIR, '_converters', '_movestats.json'), 'utf8'));
  } catch { return {}; }
}

// slug → [hp, atk, def, spa, spd, spe] base stats for ALL species (from
// _converters/_build-stats.mjs). Array order matches POKEMON_DB's `s` array
// exactly. Bundled so the stat editor / stat bars / BST resolve OFFLINE for
// every species — POKEMON_DB only covers ~Gen ≤4, so Gen 5+ previously needed a
// live PokeAPI backfill (worst in Ultra Sun/Ultra Moon). pokeInfo falls back to
// this for STATS ONLY (gen-correct typing/abilities still come from backfill).
function loadStatsBySlug() {
  try {
    return JSON.parse(readFileSync(join(SCRIPT_DIR, '_converters', '_stats.json'), 'utf8'));
  } catch { return {}; }
}

// Global forward-evolution map: slug → [[targetSlug, method], ...] (all branches),
// from _converters/build-evo-index.mjs. Bundled so the app knows every species'
// full evolution line OFFLINE without a PokeAPI backfill — drives the pre-cache
// evolution-line forward-walk (cache every reachable form's moveset) and the
// pokeInfo `.e` fallback (Gen 5+ evo recs / evo-timing advice work offline).
function loadEvoBySlug() {
  try {
    return JSON.parse(readFileSync(join(SCRIPT_DIR, '_converters', '_evo.json'), 'utf8'));
  } catch { return {}; }
}

// The slugs/IDs PokeAPI actually serves (from _converters/fetch-valid-slugs.mjs).
// Bundled so the offline pre-cache enumeration can skip URLs that would 404
// (fakemon, custom hack moves, form-only species-endpoints, evolution-chain
// gaps), keeping the precache "failed" count near zero. Arrays here; index.html
// builds Sets at startup.
function loadValidApi() {
  try {
    return JSON.parse(readFileSync(join(SCRIPT_DIR, '_converters', '_valid-api.json'), 'utf8'));
  } catch { return { pokemon: [], species: [], move: [], evoChain: [] }; }
}

// Per-game location → species index for the PokeAPI-region games (from
// _converters/build-region-species-index.mjs). Lets the encounter rail's
// "search locations & species" filter cover those games completely + offline —
// their panel renders live PokeAPI data that isn't fetched until click time.
function loadRegionSpeciesIndex() {
  try {
    return JSON.parse(readFileSync(join(SCRIPT_DIR, '_converters', '_region-species.json'), 'utf8'));
  } catch { return {}; }
}

// Form-default species whose display name slugifies (via the app's speciesSlug)
// to a FORM slug, e.g. "Wishiwashi"→wishiwashi-solo, "Mimikyu"→mimikyu-disguised.
// Both dexIdBySlug (sprite id) and typesBySlug are keyed by the BASE slug, so
// without these aliases the form slug misses → no sprite / no type badge until
// the runtime PokeAPI backfill lands. Mirrors the app's FORM_DEFAULTS set.
const FORM_SLUG_ALIASES = {
  'minior-red-meteor':'minior','eiscue-ice':'eiscue','wishiwashi-solo':'wishiwashi',
  'basculin-red-striped':'basculin','meowstic-male':'meowstic','morpeko-full-belly':'morpeko',
  'pumpkaboo-average':'pumpkaboo','oricorio-baile':'oricorio','gourgeist-average':'gourgeist',
  'mimikyu-disguised':'mimikyu','toxtricity-amped':'toxtricity','indeedee-male':'indeedee',
  'wormadam-plant':'wormadam','urshifu-single-strike':'urshifu'
};
function applyFormAliases(map) {
  for (const [form, base] of Object.entries(FORM_SLUG_ALIASES)) {
    if (map[base] != null && map[form] == null) map[form] = map[base];
  }
  return map;
}

function readDir(sub) {
  const dir = join(DATA_ROOT, sub);
  const out = {};
  for (const name of readdirSync(dir)) {
    if (!name.toLowerCase().endsWith('.txt')) continue;
    out[gameKey(name)] = norm(readFileSync(join(dir, name), 'utf8'));
  }
  return out;
}

// Pre-parsed JSON data folders (e.g. learnsets/). Each file's basename (sans
// .json) is the bundle key. Folder may be absent in older snapshots → empty map.
function readJsonDir(sub) {
  const dir = join(DATA_ROOT, sub);
  const out = {};
  let names;
  try { names = readdirSync(dir); } catch (e) { return out; }
  for (const name of names) {
    if (!name.toLowerCase().endsWith('.json')) continue;
    out[basename(name, '.json')] = JSON.parse(readFileSync(join(dir, name), 'utf8'));
  }
  return out;
}

// Routes: lines fall into three buckets.
//   "Location|species,species,..."          → encounter line
//   "Location"                              → empty location (no encounters)
//   "--Location|key|battleType|TrainerName" → trainer marker referencing a leagues entry
// Lines starting with "#" are comments / region headers; "# --..." is a disabled marker.
function parseRoutes(raw) {
  const locations = [];
  const byName = new Map();
  const regions = [];
  let currentRegion = null;

  for (const rawLine of raw.split('\n')) {
    const line = rawLine.trim();
    if (!line) continue;

    if (line.startsWith('#')) {
      // Pull out "## Foo Region" as a region marker; ignore "# --" disabled lines.
      // TWO hashes minimum. A single '#' is a comment, and treating it as a
      // region turned every explanatory note at the top of a hand-written rail
      // into a bogus region label — Gaia's showed up in the app as "Pokemon of
      // the run has nowhere to be logged." Every real region header in the data
      // set already uses '##'.
      const headingMatch = line.match(/^#{2,6}\s*(.+?)\s*$/);
      if (headingMatch && !headingMatch[1].startsWith('--')) {
        currentRegion = headingMatch[1];
        if (!regions.includes(currentRegion)) regions.push(currentRegion);
      }
      continue;
    }

    if (line.startsWith('--')) {
      // Trainer marker: --Location|key|battleType|Name
      const stripped = line.slice(2);
      const parts = stripped.split('|').map(s => s.trim());
      const [locName, key, battleType, trainerName] = parts;
      if (!locName || !key) continue;
      const loc = ensureLoc(locations, byName, locName, currentRegion);
      loc.trainers.push({
        key, battleType: battleType || null, name: trainerName || null
      });
      continue;
    }

    // Plain location line — either with species or bare
    const parts = line.split('|');
    const locName = parts[0].trim();
    if (!locName) continue;
    const loc = ensureLoc(locations, byName, locName, currentRegion);
    if (parts.length > 1) {
      const species = parts[1].split(',').map(s => s.trim()).filter(Boolean);
      // If a location appears twice with species, merge (some files repeat).
      for (const sp of species) if (!loc.species.includes(sp)) loc.species.push(sp);
    }
  }

  return { locations, regions };
}

function ensureLoc(locations, byName, name, region) {
  let loc = byName.get(name);
  if (!loc) {
    loc = { name, region: region || null, species: [], trainers: [] };
    locations.push(loc);
    byName.set(name, loc);
  }
  return loc;
}

// Leagues: blocks separated by lines beginning with "--key|...".
// Inside a block: "==key:value" are battle modifiers; species lines are pipe-separated
// with positional fields: species|level|moves|ability|item|matchup|...|nature.
// Lines starting with "#" or "===" are section / cosmetic dividers — ignored.
const CANONICAL_NATURES = new Set([
  'hardy','lonely','brave','adamant','naughty','bold','docile','relaxed','impish','lax',
  'timid','hasty','serious','jolly','naive','modest','mild','quiet','bashful','rash',
  'calm','gentle','sassy','careful','quirky'
]);
function parseLeagues(raw) {
  const trainers = {};
  let cur = null;
  let section = null;

  for (const rawLine of raw.split('\n')) {
    const line = rawLine.trim();
    if (!line) continue;

    if (line.startsWith('#')) {
      // Strip leading "#" chars and possible decorative whitespace
      const cleaned = line.replace(/^#+/, '').replace(/#+$/, '').trim();
      if (cleaned && !/^-+$/.test(cleaned)) section = cleaned;
      continue;
    }
    if (/^=+$/.test(line)) continue;

    if (line.startsWith('--')) {
      const parts = line.slice(2).split('|');
      const [key, name, theme, iconAndLoc] = parts;
      let icon = null, location = null;
      if (iconAndLoc) {
        const hashIdx = iconAndLoc.indexOf('#');
        if (hashIdx >= 0) {
          icon = iconAndLoc.slice(0, hashIdx).trim() || null;
          location = iconAndLoc.slice(hashIdx + 1).trim() || null;
        } else {
          icon = iconAndLoc.trim() || null;
        }
      }
      cur = {
        key: key.trim(),
        name: (name || '').trim() || null,
        theme: (theme || '').trim() || null,
        icon, location,
        section,
        modifiers: {},
        team: []
      };
      trainers[cur.key] = cur;
      continue;
    }

    if (!cur) continue;

    if (line.startsWith('==')) {
      // ==key:value (e.g. ==items:full-restore,full-restore or ==double:true)
      const eq = line.slice(2);
      const colon = eq.indexOf(':');
      if (colon > 0) {
        const k = eq.slice(0, colon).trim();
        const v = eq.slice(colon + 1).trim();
        cur.modifiers[k] = v;
      }
      continue;
    }

    // Species line — split on | and read positional fields.
    const parts = line.split('|').map(s => s.trim());
    const [speciesRaw, levelStr, movesStr, ability, item, matchup, ...rest] = parts;
    if (!speciesRaw) continue;
    // Some hack-ROM files annotate boss forms as `full-form>abbrev` (e.g.
    // `urshifu-single-strike>urshifu`, `absol-mega>absol-mega`). Take the LHS:
    // it carries the canonical PokeAPI slug (forms preserved, no typos like
    // `medicham-mega>medichan-mega`). The RHS is dropped — it's either
    // identical or a stripped/misspelled author annotation.
    const species = speciesRaw.includes('>') ? speciesRaw.split('>')[0].trim() : speciesRaw;
    const extra = rest.filter(Boolean);
    // 6 hack-ROM leagues files (BlazeVolt, EmeraldRunAndBun, NewGenerations,
    // RadicalRed, Unbound) encode the trainer's nature as a trailing pipe field,
    // lowercased (e.g. "...|jolly"). Scan `extra` for the first match against the
    // 25 canonical natures; everything else stays in `extra` so future trailing
    // fields aren't silently swallowed.
    let nature = null;
    for (const e of extra) {
      if (CANONICAL_NATURES.has(e.toLowerCase())) { nature = e.toLowerCase(); break; }
    }
    // Level may carry an EV spread: "18@6,252,,,,252" is level 18 with those
    // EVs (blank field = 0), in HP/Atk/Def/SpA/SpD/Spe order. Number() on the
    // whole string is NaN, which fell through to null — so every boss mon with
    // a spread rendered as level 0. 224 entries in the Unbound league file alone
    // were affected, which is most of that game's bosses.
    let level = null, memberEvs = null;
    if (levelStr) {
      const at = levelStr.indexOf('@');
      const n = parseInt(at >= 0 ? levelStr.slice(0, at) : levelStr, 10);
      level = Number.isFinite(n) ? n : null;
      if (at >= 0) {
        const spread = levelStr.slice(at + 1).split(',')
          .map(s => { const v = parseInt(s.trim(), 10); return Number.isFinite(v) ? v : 0; });
        while (spread.length < 6) spread.push(0);
        if (spread.some(v => v > 0)) memberEvs = spread.slice(0, 6);
      }
    }
    const member = {
      species,
      level,
      evs: memberEvs,
      moves: movesStr ? movesStr.split(',').map(m => m.trim()).filter(Boolean) : [],
      ability: ability || null,
      item: item || null,
      matchup: matchup || null,
      nature,
      extra
    };
    cur.team.push(member);
  }

  return { trainers };
}

// Patches: organised by "--section" markers. Each section has its own positional schema;
// we tag known ones and store the rest as raw field arrays so nothing is lost.
function parsePatches(raw) {
  const sections = {};
  let curSection = null;

  for (const rawLine of raw.split('\n')) {
    const line = rawLine.trim();
    if (!line) continue;

    if (line.startsWith('--')) {
      curSection = line.slice(2).trim();
      if (!sections[curSection]) sections[curSection] = [];
      continue;
    }
    if (!curSection) continue;

    const fields = line.split('|').map(s => s.trim());
    const entry = decodePatchRow(curSection, fields);
    sections[curSection].push(entry);
  }

  return sections;
}

function decodePatchRow(section, fields) {
  const raw = fields;
  switch (section) {
    case 'item':
      // key|replaces|description
      return { key: raw[0] || null, replaces: raw[1] || null, description: raw[2] || null, raw };
    case 'move':
      // Two known shapes:
      //   name||power                                          (blazevolt)
      //   name|type|power|description|category|displayName     (unbound, glazed)
      return {
        name: raw[0] || null,
        type: raw[1] || null,
        power: raw[2] ? Number(raw[2]) || null : null,
        description: raw[3] || null,
        category: raw[4] || null,
        displayName: raw[5] || null,
        raw
      };
    case 'ability':
      return { name: raw[0] || null, description: raw[1] || null, raw };
    case 'pokemon':
      // Two distinct shapes coexist under "--pokemon":
      //   (A) Glazed-style form linkage:
      //         |charizard||charmander>charizard-mega-x,charizard-mega-y
      //         fields → ['', 'charizard', '', 'charmander>forms']
      //   (B) Blazevolt-style stat overrides:
      //         ,,,95,,90|butterfree
      //         fields → [',,,95,,90', 'butterfree']  (leading field is a
      //         6-position hp,atk,def,spa,spd,spe CSV; blanks = no change)
      // Discriminator: if the leading field is non-empty and parses entirely
      // as numeric-or-empty CSV, treat as a stat override.
      {
        const isStatOverride = raw[0] && /^[\d,\s]*$/.test(raw[0]) && raw[0].includes(',');
        if (isStatOverride) {
          const parts = raw[0].split(',').map(s => s.trim());
          const stats = parts.map(p => p === '' ? null : (Number(p) || null));
          return { kind: 'stat-override', species: raw[1] || null, stats, raw };
        }
        const species = raw[0] || raw[1] || null;
        const linkage = raw[3] || raw[2] || '';
        let from = null, forms = [];
        if (linkage) {
          const gt = linkage.indexOf('>');
          if (gt >= 0) {
            from = linkage.slice(0, gt).trim() || null;
            forms = linkage.slice(gt + 1).split(',').map(s => s.trim()).filter(Boolean);
          } else {
            from = linkage.trim() || null;
          }
        }
        return { kind: 'form-linkage', species, from, forms, raw };
      }
    case 'fakemon':
      // stats|displayName|key|types|spriteSource|baseForm
      return {
        stats: raw[0] ? raw[0].split(',').map(n => Number(n) || null) : [],
        displayName: raw[1] || null,
        key: raw[2] || null,
        types: raw[3] ? raw[3].split(',').map(s => s.trim()).filter(Boolean) : [],
        spriteSource: raw[4] || null,
        baseForm: raw[5] || null,
        raw
      };
    default:
      return { raw };
  }
}

// Encounter tables (USUM and any future ROM-dump encounter blocks). Format:
//   "Map: <id> - <Name> [(<SubArea>)] [/ <id> - <Name> ...]"  → header; sub-area
//      in parens is added as its own alias, and multi-map segments share the block.
//   "Table N (Day|Night):"                                    → which time slot follows
//   "Encounters (Levels A-B): Sp1 (X%), Sp2 (Y%), ..."        → the wild slots we keep
//   "SOS Slot N (Levels A-B): Sp1 (X%), ..."                  → SOS-call summon slots
//   "Additional SOS encounters: SpA, SpB" | "(None)"          → SOS-exclusive species
//      SOS species not already in the table's normal slots are emitted as a
//      separate method:'sos' pool (Gen 7 SM/USUM ally summons). "(None)" adds none.
// "X (Forme 1)" is mapped to the Alolan variant ("Alolan X") for the known set of
// Gen 1 species that received Alolan formes; non-Alolan formes have their suffix
// stripped because the rest of the app doesn't distinguish them.
function parseEncounterTables(raw) {
  const ALOLAN_FORME_1 = new Set([
    'Rattata','Raticate','Raichu','Sandshrew','Sandslash','Vulpix','Ninetales',
    'Diglett','Dugtrio','Meowth','Persian','Geodude','Graveler','Golem',
    'Grimer','Muk','Exeggutor','Marowak'
  ]);
  // byName[loc].pools is an array of { mapId, tableN, lvMin, lvMax,
  // morning:[], day:[], night:[] }. Preserving per-table identity lets the
  // renderer group by level-range so each pool sums to ~100% instead of
  // merging walking + surf + fish into one >100% list. Morning is Gen 2
  // (GS/Crystal) specific; BDSP/USUM only emit Day and Night.
  const byName = {};
  const ensureLoc = (name) => {
    if (!byName[name]) byName[name] = { pools: [] };
    return byName[name];
  };
  // Current pool key: per Map block + Table number, shared across all
  // time-of-day entries (Morning/Day/Night) of the same Table within the
  // same block.
  let curPoolKey = null;
  const poolsByKeyByLoc = {};
  const getOrCreatePool = (name, mapId, tableN, lvMin, lvMax, method) => {
    const loc = ensureLoc(name);
    const idx = poolsByKeyByLoc[name] = poolsByKeyByLoc[name] || {};
    const key = `${mapId}#${tableN}`;
    if (idx[key]) {
      // First time-of-day entry of the table may have provided null method;
      // a later one may have a real method tag — keep it.
      if (method && !idx[key].method) idx[key].method = method;
      return idx[key];
    }
    // subZone is set later by the caller when the pool is stored under a
    // parent location and the Map header had a parenthetical (e.g.,
    // "Hau'oli City (Beachfront)"). Defaults to null.
    const pool = { mapId, tableN, lvMin, lvMax, morning: [], day: [], night: [], method: method || null, subZone: null };
    loc.pools.push(pool);
    idx[key] = pool;
    return pool;
  };
  const addEnc = (pool, tk, species, chance) => {
    const bucket = pool[tk];
    const existing = bucket.find(e => e.species === species);
    if (existing) {
      existing.chance = Math.max(existing.chance, chance);
    } else {
      bucket.push({ species, chance });
    }
  };
  const normSpecies = (s) => {
    if (!s || s === '(None)') return null;
    const m = s.match(/^(.+?)\s+\(Forme\s+\d+\)$/);
    if (m) {
      const base = m[1].trim();
      if (ALOLAN_FORME_1.has(base)) return 'Alolan ' + base;
      return base;
    }
    return s;
  };

  // SOS-call collection (Gen 7 SM/USUM). When an ally is summoned via an SOS
  // call, a separate slot table applies — some species (Butterfree, Sudowoodo,
  // Goomy, Castform, …) are ONLY obtainable this way. We collect them into a
  // per-table pool with method 'sos', deduped against the parent table's normal
  // slots so the SOS section carries only species not otherwise catchable there.
  // Two source line shapes feed this:
  //   "SOS Slot N (Levels X-Y): Sp (P%), ..."  → species with a summon rate
  //   "Additional SOS encounters: SpA, SpB"     → SOS-exclusive species, no rate
  //   "Additional SOS encounters: (None)"        → nothing to add
  // sosByKey[mapId#tableN] = { day: Map<species,chance>, night: Map, morning: Map }
  const sosByKey = {};
  const sosPoolInfo = {};  // mapId#tableN → { lvMin, lvMax, method, subZoneByName }
  const getSosBucket = (mapId, tableN, time) => {
    const key = `${mapId}#${tableN}`;
    if (!sosByKey[key]) sosByKey[key] = { morning: new Map(), day: new Map(), night: new Map() };
    return sosByKey[key][time];
  };
  const addSos = (mapId, tableN, time, species, chance) => {
    if (!species) return;
    const bucket = getSosBucket(mapId, tableN, time);
    // Keep the highest rate seen across the seven summon slots; rate-less
    // "Additional" species come in with chance 0 and stay 0 unless a slot line
    // also lists them with a real rate.
    const prev = bucket.has(species) ? bucket.get(species) : -1;
    if (chance > prev) bucket.set(species, chance);
  };

  let currentNames = [];
  let currentSubZoneByParent = {};  // parent-location-name → sub-zone label from the parenthetical, for tagging pools
  let currentMapId = null;
  let currentTableN = null;
  let currentMethod = null;
  let currentTime = null;

  for (const rawLine of raw.split('\n')) {
    const line = rawLine.trim();
    if (!line) continue;

    if (line.startsWith('Map: ')) {
      currentNames = [];
      currentSubZoneByParent = {};
      const segs = line.slice(5).split(' / ');
      currentMapId = null;
      for (const seg of segs) {
        const m = seg.match(/^(\d+)\s*-\s*(.+)$/);
        if (!m) continue;
        if (currentMapId == null) currentMapId = m[1]; // primary id for pool keys
        const full = m[2].trim();
        const par = full.match(/^(.+?)\s*\((.+?)\)\s*$/);
        if (par) {
          const parent = par[1].trim();
          const sub = par[2].trim();
          currentNames.push(parent);
          currentNames.push(sub);
          // Collect every sub-zone named for this parent in the current Map
          // block. Some pk3DS dumps combine multiple maps in one header (e.g.,
          // "Map: 008 - Hau'oli City (Shopping District) / 009 - Hau'oli City
          // (Marina)" — both sub-zones share the same encounter data, so the
          // pool should be tagged with both.
          if (!currentSubZoneByParent[parent]) currentSubZoneByParent[parent] = [];
          if (!currentSubZoneByParent[parent].includes(sub)) currentSubZoneByParent[parent].push(sub);
        } else {
          currentNames.push(full);
        }
      }
      currentNames = [...new Set(currentNames)];
      currentTableN = null;
      currentMethod = null;
      currentTime = null;
      continue;
    }

    if (line.startsWith('Table ')) {
      const tn = line.match(/^Table\s+(\d+)/);
      // Optional method tag in [brackets]: "Table 1 [grass] (Day):" — when present,
      // the renderer can group pool sections by method and label them properly.
      const methodMatch = line.match(/\[([^\]]+)\]/);
      // (All) — games with no day/night cycle in wild encounters (XY, SwSh).
      // Treated as `day` so it lands in the same bucket the renderer surfaces
      // when no Night data exists — the user sees one phase, no toggle.
      const tm = line.match(/\((Morning|Day|Night|All)\)/);
      currentTableN = tn ? +tn[1] : null;
      currentMethod = methodMatch ? methodMatch[1].trim() : null;
      const rawTime = tm ? tm[1].toLowerCase() : null;
      currentTime = rawTime === 'all' ? 'day' : rawTime;
      continue;
    }

    if (line.startsWith('Encounters (')) {
      if (!currentTime || !currentNames.length || currentMapId == null || currentTableN == null) continue;
      // Accept either a range ("Levels 7-9") or a single level ("Levels 7").
      // Fixed-level encounters (swarms) list one level — without the optional
      // second group these lines were skipped, dropping the whole pool.
      const lv = line.match(/Levels?\s+(\d+)(?:\s*-\s*(\d+))?/);
      if (!lv) continue;
      const lvMin = +lv[1], lvMax = lv[2] != null ? +lv[2] : +lv[1];
      const after = line.slice(line.indexOf(':') + 1);
      // Lazy match: "<name> (NN%)" pairs separated by ", ". Lazy quantifier lets the
      // inner "(Forme N)" parens be absorbed into the name part before the final (NN%).
      const re = /([^,]+?)\s*\((\d+)%\)\s*(?:,|$)/g;
      const slots = [];
      let m;
      while ((m = re.exec(after)) !== null) {
        const speciesRaw = m[1].trim();
        const chance = +m[2];
        if (!chance) continue;
        const species = normSpecies(speciesRaw);
        if (!species) continue;
        slots.push({ species, chance });
      }
      if (!slots.length) continue;
      for (const name of currentNames) {
        const pool = getOrCreatePool(name, currentMapId, currentTableN, lvMin, lvMax, currentMethod);
        // Update lv range in case Day and Night entries differ (Day usually equals Night for level).
        pool.lvMin = Math.min(pool.lvMin, lvMin);
        pool.lvMax = Math.max(pool.lvMax, lvMax);
        // Tag sub-zone label only on pools stored under the PARENT name. The
        // sub-zone's own byName entry stays untagged (you're already there).
        // If multiple sub-zones share this pool, join them with " / " so the
        // label communicates the shared scope (e.g., "Shopping District / Marina").
        if (!pool.subZone && currentSubZoneByParent[name]) {
          const list = currentSubZoneByParent[name];
          pool.subZone = list.length === 1 ? list[0] : list.join(' / ');
        }
        for (const s of slots) addEnc(pool, currentTime, s.species, s.chance);
      }
    }

    // "SOS Slot N (Levels X-Y): Sp (P%), ..." — one of the seven summon slots.
    // Same "<name> (NN%)" shape as an Encounters line; accumulate every species
    // (across all 7 slots) into the per-table SOS bucket for the current time.
    if (/^SOS Slot \d/.test(line)) {
      if (!currentTime || currentMapId == null || currentTableN == null) continue;
      const lv = line.match(/Levels?\s+(\d+)(?:\s*-\s*(\d+))?/);
      const after = line.slice(line.indexOf(':') + 1);
      const re = /([^,]+?)\s*\((\d+)%\)\s*(?:,|$)/g;
      let m;
      while ((m = re.exec(after)) !== null) {
        const chance = +m[2];
        const species = normSpecies(m[1].trim());
        if (!species) continue;
        addSos(currentMapId, currentTableN, currentTime, species, chance || 0);
      }
      const info = sosPoolInfo[`${currentMapId}#${currentTableN}`] || (sosPoolInfo[`${currentMapId}#${currentTableN}`] = {});
      if (lv) {
        const a = +lv[1], b = lv[2] != null ? +lv[2] : +lv[1];
        info.lvMin = info.lvMin == null ? a : Math.min(info.lvMin, a);
        info.lvMax = info.lvMax == null ? b : Math.max(info.lvMax, b);
      }
      continue;
    }

    // "Additional SOS encounters: SpA, SpB" (or "(None)") — SOS-exclusive
    // species with NO summon rate. Registered at rate 0 (like SV species) so
    // they surface in the SOS section without a bogus percentage.
    if (line.startsWith('Additional SOS encounters:')) {
      if (!currentTime || currentMapId == null || currentTableN == null) continue;
      const after = line.slice(line.indexOf(':') + 1).trim();
      if (after && after !== '(None)') {
        for (const raw of after.split(',')) {
          const species = normSpecies(raw.trim());
          if (species) addSos(currentMapId, currentTableN, currentTime, species, 0);
        }
      }
      continue;
    }
  }

  // Emit an SOS pool per table that has SOS-exclusive species. A species is
  // "SOS-exclusive" for a table+time only if it is NOT already in that table's
  // normal-slot bucket at the same time (dedupe) — the SOS section should carry
  // only species you can't otherwise get there. The pool inherits the parent
  // table's level range, method-independent (its own method is 'sos'), and
  // sub-zone from the parent pool stored under each location name.
  for (const [name, loc] of Object.entries(byName)) {
    // Index the parent (non-SOS) pools of this location by mapId#tableN so we
    // can read their normal species (for dedupe) and inherit level/subZone.
    const parentByKey = {};
    for (const pool of loc.pools) {
      if (pool.method === 'sos') continue;
      parentByKey[`${pool.mapId}#${pool.tableN}`] = pool;
    }
    const sosPools = [];
    for (const [key, times] of Object.entries(sosByKey)) {
      const parent = parentByKey[key];
      if (!parent) continue; // this location doesn't carry this table
      const [mapId, tableNStr] = key.split('#');
      const tableN = +tableNStr;
      const info = sosPoolInfo[key] || {};
      const lvMin = parent.lvMin != null ? parent.lvMin : (info.lvMin != null ? info.lvMin : 0);
      const lvMax = parent.lvMax != null ? parent.lvMax : (info.lvMax != null ? info.lvMax : lvMin);
      const sosPool = {
        mapId, tableN, lvMin, lvMax,
        morning: [], day: [], night: [],
        method: 'sos', subZone: parent.subZone || null,
      };
      let any = false;
      for (const tk of ['morning', 'day', 'night']) {
        const normalSpecies = new Set((parent[tk] || []).map(e => e.species));
        for (const [species, chance] of times[tk]) {
          if (normalSpecies.has(species)) continue; // already catchable normally here
          sosPool[tk].push({ species, chance });
          any = true;
        }
      }
      // The generic (non-grass) method renderer only reads the `day` bucket, so
      // mirror any night-only SOS species into `day` when the parent table has
      // no daytime SOS data — otherwise night-exclusive SOS species would never
      // surface. (Parent tables that split Day/Night still share one SOS pool.)
      if (sosPool.day.length === 0 && sosPool.night.length) {
        sosPool.day = sosPool.night.map(e => ({ ...e }));
      } else if (sosPool.night.length === 0 && sosPool.day.length) {
        sosPool.night = sosPool.day.map(e => ({ ...e }));
      }
      if (any) sosPools.push(sosPool);
    }
    for (const sp of sosPools) loc.pools.push(sp);
  }

  return { byName };
}

function buildBundle() {
  console.log(`[build-data] reading from ${DATA_ROOT}`);
  const routesRaw = readDir('routes');
  const leaguesRaw = readDir('leagues');
  const patchesRaw = readDir('patches');
  const encTablesRaw = readDir('encounter-tables');

  const routes = {};
  for (const [k, v] of Object.entries(routesRaw)) routes[k] = parseRoutes(v);
  const leagues = {};
  for (const [k, v] of Object.entries(leaguesRaw)) leagues[k] = parseLeagues(v);
  const patches = {};
  for (const [k, v] of Object.entries(patchesRaw)) patches[k] = parsePatches(v);
  const encounterTables = {};
  for (const [k, v] of Object.entries(encTablesRaw)) encounterTables[k] = parseEncounterTables(v);

  // ROM-extracted level-up learnset overrides (Drayano hacks rewrite learnsets,
  // so PokeAPI's vanilla data is wrong — e.g. Caterpie's Struggle Bug). Already
  // parsed JSON: { "<species-slug>": [ [level, "move-slug"], ... ] }. Layered on
  // top of PokeAPI at runtime by fetchLearnset for games with dataSources.learnsets.
  const learnsets = readJsonDir('learnsets');

  // Cross-reference: for each routes file, attempt to resolve each trainer marker
  // to a matching league entry by key. Records the source game's leagues file as
  // a hint (only the same-named file is auto-linked; cross-game references are left null).
  for (const [game, data] of Object.entries(routes)) {
    const leagueData = leagues[game];
    for (const loc of data.locations) {
      for (const t of loc.trainers) {
        t.resolved = leagueData?.trainers?.[t.key] ? true : false;
      }
    }
  }

  const meta = {
    generatedAt: new Date().toISOString(),
    routeFiles: Object.keys(routes).sort(),
    leagueFiles: Object.keys(leagues).sort(),
    patchFiles: Object.keys(patches).sort(),
    encounterTableFiles: Object.keys(encounterTables).sort(),
    learnsetFiles: Object.keys(learnsets).sort()
  };

  const dexIdBySlug = applyFormAliases(loadDexIdBySlug());
  const formIdBySlug = loadFormIdBySlug();
  const typesBySlug = applyFormAliases(loadTypesBySlug());
  // slugAliases (form-slug→base-slug) lets the species PICKER skip the form-slug
  // alias keys so it doesn't list junk like "Wishiwashi Solo"; the lookup maps
  // above still carry the aliases so spriteUrl/type-badge resolve by form slug.
  const slugAliases = FORM_SLUG_ALIASES;
  const validApi = loadValidApi();
  const regionSpeciesIndex = loadRegionSpeciesIndex();
  const moveStats = loadMoveStats();
  const evoBySlug = applyFormAliases(loadEvoBySlug());
  const statsBySlug = applyFormAliases(loadStatsBySlug());
  const payload = { meta, routes, leagues, patches, encounterTables, learnsets, dexIdBySlug, formIdBySlug, typesBySlug, slugAliases, validApi, regionSpeciesIndex, moveStats, evoBySlug, statsBySlug };
  const js = `// Auto-generated by build-data.mjs — DO NOT EDIT BY HAND.\n`
    + `// Generated: ${meta.generatedAt}\n`
    + `window.NUZ_DATA = ${JSON.stringify(payload)};\n`;
  writeFileSync(OUT_PATH, js, 'utf8');

  const sizeKb = (Buffer.byteLength(js, 'utf8') / 1024).toFixed(1);
  console.log(`[build-data] wrote ${OUT_PATH} (${sizeKb} KB)`);
  console.log(`[build-data] route files: ${meta.routeFiles.length}, league files: ${meta.leagueFiles.length}, patch files: ${meta.patchFiles.length}, encounter-table files: ${meta.encounterTableFiles.length}, learnset files: ${meta.learnsetFiles.length}`);

  // Rewrite index.html's <script src="data.bundle.js"> tag with a fresh
  // cache-bust query string. The regex matches an optional existing ?v=NNN
  // so re-runs replace (not stack) the slot — exactly one ?v= survives each
  // rebuild. Date.now() is short, monotonic, and human-comparable across
  // builds, which beats an ISO string for log diff readability.
  const bust = Date.now();
  const html = readFileSync(HTML_PATH, 'utf8');
  const re = /src="data\.bundle\.js(\?v=\d+)?"/;
  if (re.test(html)) {
    const out = html.replace(re, `src="data.bundle.js?v=${bust}"`);
    writeFileSync(HTML_PATH, out, 'utf8');
    console.log(`[build-data] rewrote index.html cache-buster (?v=${bust})`);
  } else {
    console.warn(`[build-data] WARN: could not find data.bundle.js script tag in index.html`);
  }
}

buildBundle();
